name: "🎁 Publish Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'roc-roofing/VERSION.txt'

env:
  AWS_DEFAULT_REGION: us-west-2
  KUBECONFIG: ${{ github.workspace }}/infrastructure/.kube/config

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}-rocroofing-deploy
  cancel-in-progress: true

jobs:
  release:
    name: "Publish Github Release"
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - name: Compute Version
        id: version
        run: echo "::set-output name=version::$(cat roc-roofing/VERSION.txt)"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          name: "roc-roofing ${{ steps.version.outputs.version }}"
          tag: "rocroofing-${{ steps.version.outputs.version }}"
          version: "rocroofing-${{ steps.version.outputs.version }}"
          publish: true
          commitish: refs/heads/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
